### PR TITLE
Fix build_jekyll failures on Travis CI

### LINKED ISSUE #16: Figure out Travis CI failures
Travis has started throwing errors for `./go build`:

https://travis-ci.org/18F/web-design-standards/builds/106562512
https://travis-ci.org/18F/web-design-standards/builds/106737058#L247

```
$ bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
$ ./go build
/home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 45 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/travis/build/18F/web-design-standards/vendor/bundle/ruby/2.2.0', execute `gem env` for more information
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
    from /home/travis/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
    from /home/travis/.rvm/gems/ruby-2.2.3/bin/bundle:22:in `<main>'
    from /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /home/travis/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

travis-ci/travis-ci#4536 references this problem, which I think has to do with the `--path` argument and `bundler` itself not being in the `BUNDLER_PATH`.

Also: https://docs.travis-ci.com/user/caching/#Bundler

cc: @juliaelman @harrisj @afeld @rogeruiz

### PR DESCRIPTION
**Pull request by mbland**
Closes #16. Basically, since the `./go` script should already invoke `require 'bundler/setup'`, running Jekyll with `bundle exec` proves unnecessary. The test_bundler_with_path_argument test case recreates the original failure faithfully, and validates the fix.

Also updates `git_sync_and_deploy` a la 18F/pages-server#19.

cc: @afeld @ccostino @jcscottiii @harrisj @rogeruiz @juliaelman

### CODE REVIEW

**Comment by mbland** [comment]
Also FYI: @ertzeid @jbarnicle @catherinedevlin @mtorres253 @andrewmaier

File: lib/go_script/go.rb [hunk 1]
```diff
@@ -90,10 +90,11 @@ def build_jekyll(extra_args = '')
...
   def git_sync_and_deploy(commands, branch: nil)
-    exec_cmd 'git stash'
-    exec_cmd "git checkout -b #{branch}" unless branch.nil?
-    exec_cmd 'git pull'
-    exec_cmd 'bundle install' if File.exist? 'Gemfile'
+    exec_cmd 'git fetch origin #{branch}'
+    exec_cmd 'git clean -f'
+    exec_cmd "git reset --hard #{branch.nil? ? 'HEAD' : 'origin/' + branch}"
+    exec_cmd 'git submodule --sync --recursive'
+    exec_cmd 'git submodule update --init --recursive'
```
Comment (ccostino) [inline lib/go_script/go.rb:97]: Just to be clear, these two submodule commands are doing the following things:
1. Update the links to the remotes associated with the submodules themselves so that they are kept up-to-date and point to the correct repository(ies).
2.  Update each of the submodules themselves.

In both cases, recursively perform the operation for any other nested submodules.  Is my understanding correct?

**Comment by ccostino** [comment]
This is awesome @mbland, and reading the write-up of the actual explanation in #16 was very interesting.  Thanks for taking the time to look into this and getting to the bottom of it!

File: lib/go_script/go.rb (hunk 1 above)
Comment (mbland) [inline lib/go_script/go.rb:97]: Yes, though note that the submodules will get synchronized to the versions currently checked into the branch, rather than synchronized to the latest versions available (which would be `git submodule update --remote`).

The nice properties of these commands are that they are no-ops when there aren't any submodules present at all.

Comment (ccostino) [inline lib/go_script/go.rb:97]: Right, which will help keeps things stable as opposed to just pulling in the latest changes in any submodules without having vetted them first.  Thanks for verifying! :-)
